---
title: "barplot_base"
author: "Heum"
Start Date: "2019년 7년 31일"
html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
> ebuil YouTube(https://www.youtube.com/channel/UCJ49UIzNXAaxZdDNYFxNhsA/featured) study

***
-- 2019. 7. 31. 

***

  - 일변량 질적 자료 분석

### [ base::barplot() ] 
#### https://youtu.be/5NcNe4CXInY


```{r packages, include = TRUE}
library(tidyverse)
```
```{r}
head(diamonds, 3)
table(diamonds$cut)
```

```{r}
barplot(table(diamonds$cut))  # 빈도 확인 

```

  - 내림차순 sort/decreasing
```{r}
barplot(sort(table(diamonds$cut), decreasing = T))
```
  
### barplot() arguments
  
    - col   = "color"         막대의 색깔
    - main  = "title"         차트 제목
    - ylab  = "y axis name"   y축 라벨
    - xlab  = "x axis name"   x축 라벨 
    - ylim  = c(min, max)     y축의 범위
    - xlim  = c(min, max)     x축의 범위 
    - horiz = TRUE            축 방향 설정 

```{r}
barplot(sort(table(diamonds$cut), decreasing = T), 
        col = "purple", 
        main = "Cut of Diamonds", 
        ylab = "Frequency", 
        xlab = "cut", 
        ylim = c(0, 25000))
```

  - RColorBrewer 를 이용한 다양한 색깔이용
```{r}
library(RColorBrewer)
display.brewer.all(type = "seq")
```


```{r}
color.palette <- RColorBrewer::brewer.pal(n = 5, name = "Blues")

barplot(sort(table(diamonds$cut), decreasing = T), 
        col  = sort(color.palette, decreasing = F), 
        main = "Cut of Diamonds", 
        ylab = "Frequency", 
        xlab = "cut", 
        ylim = c(0, 25000))
```
  
  - horiz = TRUE  막대의 방향 변경
```{r}
barplot(sort(table(diamonds$cut), decreasing = F), 
        col   = sort(color.palette, decreasing = T),
        main  = "Cut of Diamonds", 
        ylab  = "Frequency", 
        xlab  = "cut", 
        xlim  = c(0, 25000),       # horiz에 맞추어 변경 
        horiz = TRUE)
```
  
  
### [ ggplot::geom_bar() ] 
#### https://youtu.be/EubwjZfH3lU

### geom_bar() arguments
  
    - fill  = "color"         막대의 색깔

 - 막대의 색깔지정 방법(1)
 
```{r}
ggplot(data = diamonds, mapping = aes(x = cut)) +
  geom_bar(fill = RColorBrewer::brewer.pal(n = 5, name = "Blues"))
```
    
 - 막대의 색깔지정 방법(2): 범주에 따른 색깔 
 
```{r}
ggplot(data = diamonds, mapping = aes(x = cut, fill = cut)) +
  geom_bar()
```


```{r}
ggplot(data = diamonds, mapping = aes(x = cut, fill = cut)) +
  geom_bar() +
  theme_classic() +
  labs(title = "Cut of Diamonds", 
       x     = "Cut", 
       y     = "Frequency")+
  theme(plot.title = element_text(size = 20, color = "red", face = "bold"), 
        axis.title.x = element_text(size = 15, color = "blue", face = "italic"), 
        axis.title.y = element_text(size = 15, color = "purple", face = "bold.italic", angle = 270))
```

